[Components]
  SunxiPlatformPkg/SPL/SplMain/SplMainXW711.inf

[PcdsFixedAtBuild]
  gSunxiSplTokenSpaceGuid.DramClock             | 384
  gSunxiSplTokenSpaceGuid.DramMbusClock         | 300
  gSunxiSplTokenSpaceGuid.DramType              | 3
  gSunxiSplTokenSpaceGuid.DramRankNum           | 1
  gSunxiSplTokenSpaceGuid.DramDensity           | 4096
  gSunxiSplTokenSpaceGuid.DramZq                | 123
  gSunxiSplTokenSpaceGuid.DramOdtEnable         | 0
  gSunxiSplTokenSpaceGuid.DramCas               | 9
  gSunxiSplTokenSpaceGuid.DramTpr0              | 0x42d899b7
  gSunxiSplTokenSpaceGuid.DramTpr1              | 0xa090
  gSunxiSplTokenSpaceGuid.DramTpr2              | 0x22a00
  gSunxiSplTokenSpaceGuid.DramTpr3              | 0
  gSunxiSplTokenSpaceGuid.DramTpr4              | 0
  gSunxiSplTokenSpaceGuid.DramTpr5              | 0
  gSunxiSplTokenSpaceGuid.DramEmr1              | 4
  gSunxiSplTokenSpaceGuid.DramEmr2              | 0x10
  gSunxiSplTokenSpaceGuid.DramEmr3              | 0
  gSunxiSplTokenSpaceGuid.DramDqsGatingDelay    | 0
  gSunxiSplTokenSpaceGuid.DramActiveWindowing   | 0
